---
title: "mapquery_BS833_IL2_to_BS1140"
author: "Huixin Jin"
date: "2023-02-17"
output: html_document
---

```{r}
library(Seurat)
library(Signac)
library(EnsDb.Hsapiens.v86)
library(ggplot2)
library(cowplot)
library(reticulate)
library(SingleCellExperiment)
library(tidyverse)
library(RColorBrewer)
library(scCustomize)
library(ggrepel)
library(aplot)
library(plotly)
library(processx)

set.seed(123)
```

# BS833 data
```{r}
bs833.seurat <- readRDS('/Users/jinhuixin/Master/thesis/BS833do_d2_IL2/bs833_il2_impact.rds')
bs833_d0 <- subset(bs833.seurat, subset = orig.ident == 'bs833_d0')
bs833_d2 <- subset(bs833.seurat, subset = orig.ident == 'bs833_d2')
rm(bs833.seurat)
```

# BS1140 reference data 
```{r}
bs1140.seurat <- readRDS('/Users/jinhuixin/Master/thesis/GRN/BS1140/intigrate_RNA_scenic+/bs1140_multiome_rna_and_eR_integrated_wnn_seurat_obj.rds')
```

# BS833-d0 mapquery
```{r}
transfer.anchors_d0 <- FindTransferAnchors(reference = bs1140.seurat, 
                                        query = bs833_d0, 
                                        features = VariableFeatures(bs1140.seurat, assay = 'SCT'),
                                        reference.assay = 'SCT',
                                        query.assay = 'SCT',
                                        normalization.method = 'SCT',
                                        reduction = 'cca')
bs833_d0 <- MapQuery(anchorset = transfer.anchors_d0, 
                        reference = bs1140.seurat, 
                        query = bs833_d0,
                        reference.reduction = 'eR_umap',
                        reduction.model = 'eR_umap',
                        verbose = TRUE)

celltype.predictionsd0_rna <- TransferData(anchorset = transfer.anchors_d0,
                                     refdata = bs1140.seurat$celltype_rna_sct_assay,
                                     weight.reduction = bs833_d0[['pca']], 
                                     dims = 1:50)
colnames(celltype.predictionsd0_rna)[1] <- 'predicted.id.rna' 
bs833_d0 <- AddMetaData(bs833_d0, metadata = celltype.predictionsd0_rna)

celltype.predictionsd0_eR <- TransferData(anchorset = transfer.anchors_d0,
                                     refdata = bs1140.seurat$celltype_eR,
                                     weight.reduction = bs833_d0[['pca']], 
                                     dims = 1:50)
colnames(celltype.predictionsd0_eR)[1] <- 'predicted.id.eR'
bs833_d0 <- AddMetaData(bs833_d0, metadata = celltype.predictionsd0_eR)

celltype.predictionsd0_atac <- TransferData(anchorset = transfer.anchors_d0,
                                         refdata = bs1140.seurat$celltype_atac,
                                         weight.reduction = bs833_d0[['pca']],
                                         dims = 1:50)
colnames(celltype.predictionsd0_atac)[1] <- 'predicted.id.atac'
bs833_d0 <- AddMetaData(bs833_d0, metadata = celltype.predictionsd0_atac)
```

```{r}
my_color <- brewer.pal(10, "Set3")
my_col_pal2 <- c("M-GZMK+"="#8DD3C7", "Ex"="#FFFFB3", "M-IL7R+"="#BEBADA", "GNLY+NKG7+"="#FB8072", "M-CD69+"="#80B1D3", "Naive"="#FDB462", "IKZF2+PITPNC1+"="#B3DE69", "Proliferate"="#FCCDE5", "GNLY+IKZF2+"="#D9D9D9")

p1 <- DimPlot(bs1140.seurat, reduction = 'eR_umap', group.by = 'celltype_rna_sct_assay', label = TRUE, label.size = 3, repel = TRUE, cols = my_col_pal2) + 
  NoLegend() + 
  ggtitle('Reference RNA SCT annotations on eR umap') +
  theme(plot.title = element_text(size = 12)) 
p2 <- DimPlot(bs833_d0, reduction = 'ref.umap', group.by = 'predicted.id.rna', label = TRUE, label.size = 3, repel = TRUE, cols = my_col_pal2) + 
  NoLegend() + 
  ggtitle('Query (BS833 d0) transferred \nRNA SCT labels on eR umap') +
  theme(plot.title = element_text(size = 12))
p3 <- DimPlot(bs1140.seurat, reduction = 'eR_umap', group.by = 'celltype_eR', label = TRUE, label.size = 3, repel = TRUE, cols = my_color) + 
  NoLegend() + 
  ggtitle('Reference eR annotations on eR umap') +
  theme(plot.title = element_text(size = 12))
p4 <- DimPlot(bs833_d0, reduction = 'ref.umap', group.by = 'predicted.id.eR', label = TRUE, label.size = 3, repel = TRUE, cols = my_color) + 
  NoLegend() + 
  ggtitle('Query (BS833 d0) transferred \neR labels on eR umap') +
  theme(plot.title = element_text(size = 12))
p5 <- DimPlot(bs1140.seurat, reduction = 'eR_umap', group.by = 'celltype_atac', label = TRUE, label.size = 3, repel = TRUE, cols = my_color) + 
  NoLegend() + 
  ggtitle('Reference ATAC annotations on eR umap') +
  theme(plot.title = element_text(size = 12))
p6 <- DimPlot(bs833_d0, reduction = 'ref.umap', group.by = 'predicted.id.atac', label = TRUE, label.size = 3, repel = TRUE, cols = my_color) + 
  NoLegend() + 
  ggtitle('Query (BS833 d0) transferred \nATAC labels on eR umap') +
  theme(plot.title = element_text(size = 12))
options(ggrepel.max.overlaps = Inf)
p <- (p1 / p2) | (p3 / p4) | (p5 / p6)
```

# BS833-d2 mapquery
```{r}
transfer.anchors_d2 <- FindTransferAnchors(reference = bs1140.seurat, 
                                        query = bs833_d2, 
                                        features = VariableFeatures(bs1140.seurat, assay = 'SCT'),
                                        reference.assay = 'SCT',
                                        query.assay = 'SCT',
                                        normalization.method = 'SCT',
                                        reduction = 'cca')
bs833_d2 <- MapQuery(anchorset = transfer.anchors_d2, 
                        reference = bs1140.seurat, 
                        query = bs833_d2,
                        reference.reduction = 'eR_umap',
                        reduction.model = 'eR_umap',
                        verbose = TRUE)

celltype.predictionsd2_rna <- TransferData(anchorset = transfer.anchors_d2,
                                     refdata = bs1140.seurat$celltype_rna_sct_assay,
                                     weight.reduction = bs833_d2[['pca']], 
                                     dims = 1:50)
colnames(celltype.predictionsd2_rna)[1] <- 'predicted.id.rna' 
bs833_d2 <- AddMetaData(bs833_d2, metadata = celltype.predictionsd2_rna)

celltype.predictionsd2_eR <- TransferData(anchorset = transfer.anchors_d2,
                                     refdata = bs1140.seurat$celltype_eR,
                                     weight.reduction = bs833_d2[['pca']], 
                                     dims = 1:50)
colnames(celltype.predictionsd2_eR)[1] <- 'predicted.id.eR'
bs833_d2 <- AddMetaData(bs833_d2, metadata = celltype.predictionsd2_eR)

celltype.predictionsd2_atac <- TransferData(anchorset = transfer.anchors_d2,
                                         refdata = bs1140.seurat$celltype_atac,
                                         weight.reduction = bs833_d2[['pca']],
                                         dims = 1:50)
colnames(celltype.predictionsd2_atac)[1] <- 'predicted.id.atac'
bs833_d2 <- AddMetaData(bs833_d2, metadata = celltype.predictionsd2_atac)
```

```{r}
p7 <- DimPlot(bs833_d2, reduction = 'ref.umap', group.by = 'predicted.id.rna', label = TRUE, label.size = 3, repel = TRUE, cols = my_col_pal2) + 
  NoLegend() + 
  ggtitle('Query (BS833 d2) transferred \nRNA SCT labels on eR umap') +
  theme(plot.title = element_text(size = 12))

p8 <- DimPlot(bs833_d2, reduction = 'ref.umap', group.by = 'predicted.id.eR', label = TRUE, label.size = 3, repel = TRUE, cols = my_color) + 
  NoLegend() + 
  ggtitle('Query (BS833 d2) transferred \neR labels on eR umap') +
  theme(plot.title = element_text(size = 12))

p9 <- DimPlot(bs833_d2, reduction = 'ref.umap', group.by = 'predicted.id.atac', label = TRUE, label.size = 3, repel = TRUE, cols = my_color) + 
  NoLegend() + 
  ggtitle('Query (BS833 d2) transferred \nATAC labels on eR umap') +
  theme(plot.title = element_text(size = 12))
options(ggrepel.max.overlaps = Inf)
p2 <- (p2 / p7) | (p4 / p8) | (p6 / p9)
pdf(file = './Mapquery_eR_umap_d0_d2_comparison.pdf', width = 24, height = 12)
p2
dev.off()
```

```{r}
saveRDS(bs833_d0, file = 'BS833d0_mapquery_to_BS1140_eR_umap.rds')
saveRDS(bs833_d2, file = 'BS833d2_mapquery_to_BS1140_eR_umap.rds')
```

## pie chart
```{r}
d0_cell_group_rna <- as.data.frame(table(bs833_d0$predicted.id.rna)) %>%
  mutate(Percent = Freq/sum(Freq)) 
colnames(d0_cell_group_rna)[1] <- c("celltype")
p0 <- plot_ly(d0_cell_group_rna, labels = ~celltype, values = ~Percent, type = 'pie', textposition='outside', textinfo = 'percent', colors = my_color) %>%
  layout(title = 'BS833 d0',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)) 
htmlwidgets::saveWidget(p0, 'pie_chart_bs833_d0_rna_celltype.html')
d2_cell_group_rna <- as.data.frame(table(bs833_d2$predicted.id.rna)) %>%
  mutate(Percent = Freq/sum(Freq))
colnames(d2_cell_group_rna)[1] <- c("celltype")
p2 <- plot_ly(d2_cell_group_rna, labels = ~celltype, values = ~Percent, type = 'pie', textposition='outside', textinfo = 'percent', colors = my_color) %>%
  layout(title = 'BS833 d2',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)) 
htmlwidgets::saveWidget(p2, 'pie_chart_bs833_d2_rna_celltype.html')
```

```{r}
d0_cell_group_eR <- as.data.frame(table(bs833_d0$predicted.id.eR)) %>%
  mutate(Percent = Freq/sum(Freq)) 
colnames(d0_cell_group_eR)[1] <- c("celltype")
p0 <- plot_ly(d0_cell_group_eR, labels = ~celltype, values = ~Percent, type = 'pie', textposition='outside', textinfo = 'percent', colors = my_color) %>%
  layout(title = 'BS833 d0',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)) 
htmlwidgets::saveWidget(p0, 'pie_chart_bs833_d0_eR_celltype.html')
d2_cell_group_eR <- as.data.frame(table(bs833_d2$predicted.id.eR)) %>%
  mutate(Percent = Freq/sum(Freq))
colnames(d2_cell_group_eR)[1] <- c("celltype")
p2 <- plot_ly(d2_cell_group_eR, labels = ~celltype, values = ~Percent, type = 'pie', textposition='outside', textinfo = 'percent', colors = my_color) %>%
  layout(title = 'BS833 d2',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)) 
htmlwidgets::saveWidget(p2, 'pie_chart_bs833_d2_eR_celltype.html')
```




